package hack




























































}	fmt.Println("README.md updated successfully")	}		panic(err)	if err != nil {	err = os.WriteFile("README.md", []byte(newContent), 0644)		newContent := content[:startIdx+len(startMarker)] + "\n| Target | Description |\n|---|---|\n" + strings.Join(targets, "\n") + "\n" + content[endIdx:]	}		return		fmt.Println("Markers not found in README.md")	if startIdx == -1 || endIdx == -1 {	endIdx := strings.Index(content, endMarker)	startIdx := strings.Index(content, startMarker)	content := string(readmeContent)	}		panic(err)	if err != nil {	readmeContent, err := os.ReadFile("README.md")	sort.Strings(targets)	}		}			targets = append(targets, fmt.Sprintf("| `%s` | %s |", target, desc))			desc := matches[2]			target := matches[1]		if len(matches) == 3 {		matches := re.FindStringSubmatch(line)		line := scanner.Text()	for scanner.Scan() {	re := regexp.MustCompile(`^([a-zA-Z0-9_-]+):.*?## (.*)$`)	scanner := bufio.NewScanner(makefile)	var targets []string	defer makefile.Close()	}		panic(err)	if err != nil {	makefile, err := os.Open("Makefile")func main() {)	endMarker   = "<!-- END_MAKEFILE_DOCS -->"	startMarker = "<!-- BEGIN_MAKEFILE_DOCS -->"const ()	"strings"	"sort"	"regexp"	"os"	"fmt"	"bufio"import (package main